### ISSUE TITLE
Bitdefender does not like NZBhydra

### ISSUE THREAD

**Issue by Hypernut** [theotherp/nzbhydra-windows-releases#2]
Specifically the "....tray.exe". It deletes it on sight.  And if you you make an exception then the behavioral analysis kicks in moments later and deletes it anyway. Never saw this in four years of using BD.
So short of deactivating BD, no chance of using hydra, which isnt going to happen.
What the heck does NZBhydra to provoke this action?

thanks, Rob

**Comment by theotherp** [comment]
No idea. See here: https://www.virustotal.com/de/file/71f136aa79d307fb521c1cd05cde978d2f8a3e7cff7c9ba9c5a3199a60db8f13/analysis/1485265026/

That's the analysis of the latest binary. If bitdefender supports that you could send in the exe as false positive.

**Comment by Hypernut** [comment]
Its not the binary itself that is in question. I know (or at
      least am pretty sure) its not a virus. 
      
      Its the behavioral analysis that detects a "behavior" of the
      tray-exe, that it deems potentially malicious.
      As there are practically no  misfires with BD, tray-exe must do
      something unusual. Does it maybe manipulate another exe or dll in
      its path? 
    
    thanks, rob
    
    Am 24.01.2017 um 14:39 schrieb
      theotherp:
    
    
      No idea. See here: https://www.virustotal.com/de/file/71f136aa79d307fb521c1cd05cde978d2f8a3e7cff7c9ba9c5a3199a60db8f13/analysis/1485265026/
      That's the analysis of the latest binary. If bitdefender
        supports that you could send in the exe as false positive.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/theotherp/nzbhydra-windows-releases","title":"theotherp/nzbhydra-windows-releases","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/theotherp/nzbhydra-windows-releases"}},"updates":{"snippets":[{"icon":"PERSON","message":"@theotherp in #2: No idea. See here: https://www.virustotal.com/de/file/71f136aa79d307fb521c1cd05cde978d2f8a3e7cff7c9ba9c5a3199a60db8f13/analysis/1485265026/\n\nThat's the analysis of the latest binary. If bitdefender supports that you could send in the exe as false positive. "}],"action":{"name":"View Issue","url":"https://github.com/theotherp/nzbhydra-windows-releases/issues/2#issuecomment-274804724"}}}

**Comment by theotherp** [comment]
It starts another process without showing it, reads a cfg, shuts down the process if requested and restarts it. That's about it. Doesn't BitDefender say why it thinks the EXE is suspicious?

**Comment by Hypernut** [comment]
unfortunately not. It just says that "active thread control" stopped a potentially harmful action by an application.

**Comment by theotherp** [comment]
In that case you have two options: Don't use the exe or add it to the exclusion list.

**Comment by Hypernut** [comment]
:/
