### ISSUE TITLE
0.2.202 Release Broken

### ISSUE THREAD

**Issue by Alamei** [theotherp/nzbhydra-windows-releases#3]
It looks like you accidentally removed all of the core application files in the Windows version of the 0.2.202 release, leaving only the tray and service manager files in place. The good news is that, since the version.txt file isn't present, the auto-update feature won't try to push anyone onto this release. As such, it shouldn't break any existing installs, only prevent new users from installing the windows version if they try to download the latest release.

**Comment by theotherp** [comment]
Huh, How did that happen... My script failed me.

**Comment by theotherp** [comment]
Should be fixed, thanks.

**Comment by Alamei** [comment]
Confirmed fixed. It's always fun when a build script decides to throw you for a loop. 😄
