### ISSUE TITLE
Windows release has issues (Detailed below)

### ISSUE THREAD

**Issue by lyfesaver** [theotherp/nzbhydra-windows-releases#4]
Downloaded the latest windows release and unzipped it. Ran tray and it gets stuck in an endless loop of trying to launch. Finally timed it right to be able to catch it and end task in task manager. Opened command prompt and ran nzbhydra.exe by itself. Crashed and told me that the tk directory could not be found. Created and empty tk folder and ran tray. Tray launches nzbhydra.exe and opens webpage that displays the text "index.html". Right clicked on tray icon and told it to show web interface again and get a pop up message that says settings.cfg not found.

This is where I am stuck

**Comment by lyfesaver** [comment]
Launched older version as it had all the files needed, and updated inside the app.

Solution, add the rest of the files to the most recent Windows release.

**Comment by theotherp** [comment]
Sorry about that, should be fixed. My build script went haywire and deleted a bunch of files and itself :-(
