### ISSUE TITLE
0.2.217 crahses

### ISSUE THREAD

**Issue by ksbansal** [theotherp/nzbhydra-windows-releases#5]
fresh install of 0.2.217 crahses windows 7 sp1.

**Comment by ilneroviaggiatore** [comment]
Idem on windows 7 sp1. The nzbhydra.exe and NZBHydraTray.exe process endlessly open and close in Task Manager together with PING.exe process. Thanks!

**Comment by theotherp** [comment]
See https://github.com/theotherp/nzbhydra/issues/602
