### ISSUE TITLE
Serivce not starting after Windows 10 Creators edition update

### ISSUE THREAD

**Issue by rudyolph** [theotherp/nzbhydra-windows-releases#6]
I'm getting the following error when trying to start the windows service.
"Windows could not start the NzbHyrdra serice on Local Computer.  The service did not return an error. This could be an internal Windows error or an internal service error."

Then after the error the service goes into a paused state.

This started after the Windows 10 Creators edition update.

**Comment by rudyolph** [comment]
https://nssm.cc/download

NSSM - the Non-Sucking Service Manager

Windows 10 Creators Update

2017-04-26: Users of Windows 10 Creators Update should use prelease build 2.2.4-101 to avoid an issue with services failing to start. If for some reason you cannot use that build you can also set AppNoConsole=1 in the registry, noting that applications which expect a console window may behave unexpectedly.

Thanks to Sebasian Krause for the initial diagnosis.

**Comment by rudyolph** [comment]
I manually installed the pre-release version and the service is now starting correctly again.  Please update to the release of nssm.exe.

**Comment by theotherp** [comment]
Sorry, I missed this issue because I usually only look at the ones in the main repository. And then I lost some of my source code which is why the fix for this got lost too.

**Comment by theotherp** [comment]
Should be fixed.
