### ISSUE TITLE
Cannot search via browser UI

### ISSUE THREAD

**Issue by kmccormi** [theotherp/nzbhydra-windows-releases#7]
Hi, I have started to see fairly consistent browser error messages when attempting to search from the main browser interface. The problem (possibly) started after I added some Jackett entries, although I disabled/deleted those entries and still got the error messages.

What I 'm seeing:
500, 502 and 503 Internal Server error messages., sometimes with unicode errors reported in the logs, sometimes the errors state no data received from server or forwarder, sometimes no supporting info.
Other times it just sits on 'searching' until I restart.

If I restart NZBHydra I will often get one or two searches before the errors occur, sometimes not.

What I've tried:
I backed up the settings and database, uninstalled and reinstalled the latest Windows release, then restored from the backup; I went through the settings for each indexer and re-checked for capabilities. Any indexer that couldn't be checked was then disabled, with pre-select switched off.

I'm running on Win 10 64, and running NZBHydra from NZBHydra Tray.exe, not as a service.

The latest (Debug) logs are enclosed, and thanks for taking a look at it
[logfile.txt](https://github.com/theotherp/nzbhydra-windows-releases/files/1100992/logfile.txt)

**Comment by theotherp** [comment]
Sorry for the late response, I usually only take issues on the main repository.

Try disabling torrentproject.se. That's not a permanent solution, though; just to see what happens.

**Comment by kmccormi** [comment]
Tried your suggestion. Same results as before. I saw that a new release is out though, so I will update and try again. I will close out this issue and move it to the main thread if I still can't get things working.
